# Shell variables
# Generated by 'wal' and adjusted for tempus

background='#1d2021' # wall color0
foreground='#d5c4a1' # wall color7, NOTE in tempus this would be color15

# -- cpdfd
backgroundalt="#665c54" # tempus color8, also backgrounddim
foregroundalt="#d5c4a1" # tempus color7
cursorColor="#d5c4a1" # tempus color 15 and fg
cursorColor2="#1d2021" # tempus color0
# -- cpdfd

cursor='#d5c4a1' # wall foreground and color7

color0='#1d2021'
color1='#fb4934'
color2='#b8bb26'
color3='#fabd2f'
color4='#83a598'
color5='#d3869b'
color6='#8ec07c'
color7='#d5c4a1'
color8='#665c54'
color9='#fb4934'
color10='#b8bb26'
color11='#fabd2f'
color12='#83a598'
color13='#d3869b'
color14='#8ec07c'
color15='#fbf1c7'

# -- cpdfd
backgrounddim="#665c54" # color8
# -- cpdfd
