#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	bat="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query"

# This alias is important. It enables the `pauseallmpv` command.
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

# Some other stuff
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	weath="less -S ~/.local/share/weatherreport" \

CFGP=$XDG_CONFIG_HOME
alias ev="vim ~/.vim/vimrc"
alias ezsh="vim $CFGP/zsh/.zshrc"
alias ealiases="vim $ZSH/custom/aliases.zsh"
alias eozsh="vim $ZSH/.oh-my-zsh.sh"

# dotfiles
alias ereadme="vim ~/dotfiles/README.md"
alias cdd="cd ~/dotfiles"

alias szsh="source $CFGP/zsh/.zshrc"

# arch git alias does not work. Make a link from vim to vi in /usr/bin
# Command aliases
alias fd="fdfind"
alias clr="clear"
alias dirs="dirs -v"

# ZSH guide pdf copy helper
alias %=' '

# Startx
alias sxb='startx ~/.xinitrc'
alias sxx='startx ~/.xinitrc xfce'

# Aliases with oh my zsh
##alias -='cd -'
#alias ...=../..
#alias ....=../../..
#alias .....=../../../..
#alias ......=../../../../..
#alias 1='cd -'
#alias 2='cd -2'
#alias 3='cd -3'
#alias 4='cd -4'
#alias 5='cd -5'
#alias 6='cd -6'
#alias 7='cd -7'
#alias 8='cd -8'
#alias 9='cd -9'
#alias _='sudo '
#alias afind='ack -il'
#alias clr=clear
#alias cp='nocorrect cp'
#alias g=git
#alias ga='git add'
#alias gaa='git add --all'
#alias gap='git apply'
#alias gapa='git add --patch'
#alias gau='git add --update'
#alias gav='git add --verbose'
#alias gb='git branch'
#alias gbD='git branch -D'
#alias gba='git branch -a'
#alias gbd='git branch -d'
#alias gbda='git branch --no-color --merged | command grep -vE "^(\+|\*|\s*(master|develop|dev)\s*$)" | command xargs -n 1 git branch -d'
#alias gbl='git blame -b -w'
#alias gbnm='git branch --no-merged'
#alias gbr='git branch --remote'
#alias gbs='git bisect'
#alias gbsb='git bisect bad'
#alias gbsg='git bisect good'
#alias gbsr='git bisect reset'
#alias gbss='git bisect start'
#alias gc='git commit -v'
#alias 'gc!'='git commit -v --amend'
#alias gca='git commit -v -a'
#alias 'gca!'='git commit -v -a --amend'
#alias gcam='git commit -a -m'
#alias 'gcan!'='git commit -v -a --no-edit --amend'
#alias 'gcans!'='git commit -v -a -s --no-edit --amend'
#alias gcb='git checkout -b'
#alias gcd='git checkout develop'
#alias gcf='git config --list'
#alias gcl='git clone --recurse-submodules'
#alias gclean='git clean -id'
#alias gcm='git checkout master'
#alias gcmsg='git commit -m'
#alias 'gcn!'='git commit -v --no-edit --amend'
#alias gco='git checkout'
#alias gcount='git shortlog -sn'
#alias gcp='git cherry-pick'
#alias gcpa='git cherry-pick --abort'
#alias gcpc='git cherry-pick --continue'
#alias gcs='git commit -S'
#alias gcsm='git commit -s -m'
#alias gd='git diff'
#alias gdca='git diff --cached'
#alias gdct='git describe --tags $(git rev-list --tags --max-count=1)'
#alias gdcw='git diff --cached --word-diff'
#alias gds='git diff --staged'
#alias gdt='git diff-tree --no-commit-id --name-only -r'
#alias gdw='git diff --word-diff'
#alias gf='git fetch'
#alias gfa='git fetch --all --prune'
#alias gfg='git ls-files | grep'
#alias gfo='git fetch origin'
#alias gg='git gui citool'
#alias gga='git gui citool --amend'
#alias ggpull='git pull origin "$(git_current_branch)"'
#alias ggpur=ggu
#alias ggpush='git push origin "$(git_current_branch)"'
#alias ggsup='git branch --set-upstream-to=origin/$(git_current_branch)'
#alias ghh='git help'
#alias gignore='git update-index --assume-unchanged'
#alias gignored='git ls-files -v | grep "^[[:lower:]]"'
#alias gist='nocorrect gist'
#alias git-svn-dcommit-push='git svn dcommit && git push github master:svntrunk'
#alias gk='\gitk --all --branches'
#alias gke='\gitk --all $(git log -g --pretty=%h)'
#alias gl='git pull'
#alias glg='git log --stat'
#alias glgg='git log --graph'
#alias glgga='git log --graph --decorate --all'
#alias glgm='git log --graph --max-count=10'
#alias glgp='git log --stat -p'
#alias glo='git log --oneline --decorate'
#alias globurl='noglob urlglobber '
#alias glod='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'\'
#alias glods='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'\'' --date=short'
#alias glog='git log --oneline --decorate --graph'
#alias gloga='git log --oneline --decorate --graph --all'
#alias glol='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'
#alias glola='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'' --all'
#alias glols='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'' --stat'
#alias glp=_git_log_prettily
#alias glum='git pull upstream master'
#alias gm='git merge'
#alias gma='git merge --abort'
#alias gmom='git merge origin/master'
#alias gmt='git mergetool --no-prompt'
#alias gmtvim='git mergetool --no-prompt --tool=vimdiff'
#alias gmum='git merge upstream/master'
#alias gp='git push'
#alias gpd='git push --dry-run'
#alias gpf='git push --force-with-lease'
#alias 'gpf!'='git push --force'
#alias gpoat='git push origin --all && git push origin --tags'
#alias gpristine='git reset --hard && git clean -dfx'
#alias gpsup='git push --set-upstream origin $(git_current_branch)'
#alias gpu='git push upstream'
#alias gpv='git push -v'
#alias gr='git remote'
#alias gra='git remote add'
#alias grb='git rebase'
#alias grba='git rebase --abort'
#alias grbc='git rebase --continue'
#alias grbd='git rebase develop'
#alias grbi='git rebase -i'
#alias grbm='git rebase master'
#alias grbs='git rebase --skip'
#alias grep='grep  --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}'
#alias grev='git revert'
#alias grh='git reset'
#alias grhh='git reset --hard'
#alias grm='git rm'
#alias grmc='git rm --cached'
#alias grmv='git remote rename'
#alias groh='git reset origin/$(git_current_branch) --hard'
#alias grrm='git remote remove'
#alias grs='git restore'
#alias grset='git remote set-url'
#alias grss='git restore --source'
#alias grt='cd "$(git rev-parse --show-toplevel || echo .)"'
#alias gru='git reset --'
#alias grup='git remote update'
#alias grv='git remote -v'
#alias gsb='git status -sb'
#alias gsd='git svn dcommit'
#alias gsh='git show'
#alias gsi='git submodule init'
#alias gsps='git show --pretty=short --show-signature'
#alias gsr='git svn rebase'
#alias gss='git status -s'
#alias gst='git status'
#alias gsta='git stash push'
#alias gstaa='git stash apply'
#alias gstall='git stash --all'
#alias gstc='git stash clear'
#alias gstd='git stash drop'
#alias gstl='git stash list'
#alias gstp='git stash pop'
#alias gsts='git stash show --text'
#alias gsu='git submodule update'
#alias gsw='git switch'
#alias gswc='git switch -c'
#alias gtl='gtl(){ git tag --sort=-v:refname -n -l "${1}*" }; noglob gtl'
#alias gts='git tag -s'
#alias gtv='git tag | sort -V'
#alias gunignore='git update-index --no-assume-unchanged'
#alias gunwip='git log -n 1 | grep -q -c "\-\-wip\-\-" && git reset HEAD~1'
#alias gup='git pull --rebase'
#alias gupa='git pull --rebase --autostash'
#alias gupav='git pull --rebase --autostash -v'
#alias gupv='git pull --rebase -v'
#alias gwch='git whatchanged -p --abbrev-commit --pretty=medium'
#alias gwip='git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign -m "--wip-- [skip ci]"'
##alias history=omz_history
#alias l='ls -lah'
#alias la='ls -lAh'
#alias ll='ls -lh'
#alias ls='ls --color=tty'
#alias lsa='ls -lah'
#alias man='nocorrect man'
#alias md='mkdir -p'
#alias mkdir='nocorrect mkdir'
#alias mv='nocorrect mv'
#alias mysql='nocorrect mysql'
#alias rd=rmdir
#alias run-help=man
#alias sudo='nocorrect sudo'
#alias which-command=whence
