#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	bat="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	ll="ls -alF" \
	la="ls -A" \
	l="ls -CF" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	sdn="sudo shutdown -h now" \
	srn="sudo reboot now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \


# Some other stuff
alias \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \

# arch git alias does not work. Make a link from vim to vi in /usr/bin
# Command aliases
alias fd="fdfind"
alias clr="clear"
alias dirs="dirs -v"

# ZSH guide pdf copy helper
alias %=' '

# Startx
alias sxb='startx'

#alias | grep -i git | sort -R | head -10

# Command aliases, suffix aliases, global aliases
#alias -s {yml,yaml}=vim
alias -g G='| grep -i'
alias -g M='| more'
