#! /bin/sh

. $(colors-get-base16)

# Truncate a couple of common commands that are used herein.
_bc() {
	bspc config "$@"
}

_check() {
	command -v "$1" > /dev/null
}

launchpolybar &

bspc monitor -d I II III IV V VI VII VIII IX X

# window management
# -----------------
_bc border_width 2
_bc window_gap 4
_bc split_ratio 0.50
_bc single_monocle false
_bc borderless_monocle true
_bc gapless_monocle false
_bc focus_follows_pointer false
_bc pointer_follows_monitor true
_bc pointer_modifier mod1
_bc pointer_action1 move
_bc pointer_action2 resize_side
_bc click_to_focus any
_bc swallow_first_click false
_bc initial_polarity first_child
_bc ignore_ewmh_focus true
_bc automatic_scheme spiral

## Set the border colors.
# background alt
#bspc config normal_border_color "$color8"
#bspc config active_border_color "$color3"
#bspc config focused_border_color "$color6"
# backgrouddim todo
#bspc config presel_feedback_color "$color8"

#bspc rule -a Zathura state=tiled
#bspc rule -a Gimp desktop='^5' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
