#! /bin/sh

. $(colors-get-base16)

[ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
pgrep -x panel > /dev/null || panel &

#$HOME/.config/polybar/launch.sh

#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d I II III IV V
bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
#bspc config single_monocle       true
bspc config borderless_monocle   false
bspc config gapless_monocle      true

#bspc config pointer_follows_monitor       true
#bspc config focus_follows_pointer         true

# Set the border colors.
bspc config normal_border_color "$color0"
# This does not seem to work:
bspc config active_border_color "$color2"
bspc config focused_border_color "$color11"
bspc config presel_feedback_color "$color15"

bspc rule -a Zathura state=tiled
bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
