#!/bin/bash

awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' ~/.config/sxhkd/*.sxhkdrc |
    column -t -s $'\t' | 
    dmenu -p "sxhkd help" -i -l 100
#rofi -dmenu -i -markup-rows -no-show-icons -width 1000 -lines 15 -yoffset 40
