#! /bin/sh

_bc() {
	bspc config "$@"
}

_check() {
	command -v "$1" > /dev/null
}

_xrdb(){
	echo $(xrdb -query | grep "^*$1:" | cut -d: -f2 | sed s/\\s//)
}

bspc rule -r "*"

###---Autostart---###
. $XDG_CONFIG_HOME/sxhkd/startup.mode
launchpolybar &
nm-applet &

# killall bspswallow
# pidof bspswallow | bspswallow &

bspc monitor -d I II III IV V VI VII VIII IX X

# window management
# -----------------
_bc pointer_modifier mod1
_bc pointer_action1 move
_bc pointer_action2 resize_side
_bc pointer_action3 resize_corner
_bc click_to_focus any
_bc pointer_follows_monitor true
_bc swallow_first_click false
# Can be very distracting with a touchpad
_bc focus_follows_pointer false

_bc remove_disabled_monitors true
_bc remove_unplugged_monitors true
_bc merge_overlapping_monitors true

_bc top_padding 0
_bc bottom_padding 0
_bc left_padding 0
_bc right_padding 0
_bc window_gap 4 

_bc border_width 4

_bc split_ratio 0.50

_bc single_monocle false
_bc borderless_monocle true
_bc gapless_monocle false

_bc ignore_ewmh_focus true
_bc automatic_scheme spiral
# _bc automatic_scheme alternate
# _bc automatic_scheme longest_side
_bc initial_polarity first_child
# _bc initial_polarity second_child

# colours
# -------
_bc presel_feedback_color $(_xrdb "color1")
_bc normal_border_color $(_xrdb "color0")
_bc active_border_color $(_xrdb "color0")
_bc focused_border_color $(_xrdb "color3")

#bspc rule -a Zathura state=tiled
#bspc rule -a Gimp desktop='^5' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Scratchpad according to arch wiki
bspc rule -a dropdown sticky=on state=floating hidden=on
# st -c dropdown &
